### PR TITLE
Added Blog link in NavBar

### PR DESCRIPTION
**Pull request by LalitNM**
There was no link to https://blog.stac-iitmandi.org in navigation bar of this site. I added that.

### CODE REVIEW

**Comment by LalitNM** [comment]
@akshat157 Please have a look.

**Comment by akshat157** [comment]
@LalitNM Your commit changes almost all the lines in the code (although just the formatting, which itself is important not to be changed.) which is unnecessary as it will lead to a mismatch with other files and require code to be checked line by line for any unwanted changes.

I request you to edit your PR and change only the required lines. It should take 1-2 line changes to add the blog link.

**Comment by LalitNM** [comment]
@akshat157 I have solved that problem. Is this correct now?

**Comment by abhijeetmanhas** [comment]
@LalitNM everything looks great, but you have to make the same changes to other files too, like the template, zenith, team, etc.

**Comment by LalitNM** [comment]
will do that :)

**Comment by LalitNM** [comment]
@abhijeetmanhas check now.

**Comment by abhijeetmanhas** [comment]
Lalit I have merged the changes, but next time try to have cleaner git history, less commits for small changes.
Better squash redundant commits.

**Pull request merged**
