### PR TITLE
Main-heading on tablet-like devices

### PR DESCRIPTION
**Pull request by LalitNM**
Earlier there was unnecessary smoothscroll.js file in the repository. I removed that added few lines in layout.css. This will help future develops to easily understand the code.

### CODE REVIEW

**Comment by LalitNM** [comment]
@akshat157 and @abhijeetmanhas is this helpful?

**Comment by abhijeetmanhas** [comment]
@akshat157 why we required that file earlier? was it supposed to be used somewhere? I request you if you have spare time you can review this one.

And @LalitNM if you fix U issue, please attach a screenshot.

**Comment by LalitNM** [comment]
new-stac
@abhijeetmanhas this is new-look, you can see older one on [STAC](https://stac-iitmandi.org).

**Comment by LalitNM** [comment]
Great! I did't know that. I am also against deletion now. @abhijeetmanhas what do you say?

**Comment by abhijeetmanhas** [comment]
Keep it. And clean the git history too.

**Comment by LalitNM** [comment]
@abhijeetmanhas I have changed history, now it has only one commit.

**Comment by abhijeetmanhas** [comment]
Thanks @LalitNM

**Pull request merged**
