### PR TITLE
Add statistics to index

### PR DESCRIPTION
**Pull request by MADPT**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
This is nice! Can you post a screenshot?

**Comment by MADPT** [comment]
Here you go:
image

It's responsive (1 column on smartphone, 2 on tablet and 4 on desktop).

**Comment by shreyasbapat** [comment]
How about having a lightish background color on it?

**Comment by MADPT** [comment]
@shreyasbapat do you have a color in mind?

**Comment by shreyasbapat** [comment]
Perhaps, let's leave it like that for now.

**Comment by shreyasbapat** [comment]
I will add some commits to this PR if you allow _/\_ :wink:

**Comment by shreyasbapat** [comment]
Thanks @MADPT ! I made some changes in the PR without your permission! But I guess you might be fine with it! :stuck_out_tongue:

**Comment by shreyasbapat** [comment]
image
FYI this is how it turned up to be! Thanks a ton!

**Comment by MADPT** [comment]
@shreyasbapat  of course you're allowed, this is your project xD

**Pull request merged**
