### PR TITLE
Basic Template for Archives

### PR DESCRIPTION
**Pull request by Tushar-Tyagi**
Created a template for archive with different sections for achivements, past team, trips, etc.
Currently all styling is just for testing. Different sections should be editied and cards should be filled with information.
Currently archive is still pointing to "!#" , but will link to archive.html once others complete it.
screenshot from 2019-01-29 14-28-40
screenshot from 2019-01-29 14-28-49
screenshot from 2019-01-29 14-28-55

@shreyasbapat @akshat157

### CODE REVIEW

**Comment by shreyasbapat** [comment]
@Tushar-Tyagi  there is a `.html` file in the repository named, `template.html`. All the new files have to be built on that so that we maintain a homogeneity. Can you please port this to that template?

**Comment by Tushar-Tyagi** [comment]
@shreyasbapat sure, will do

**Comment by LalitNM** [comment]
@Tushar-Tyagi are you still working on it? I want to do this?

**Comment by abhijeetmanhas** [comment]
@LalitNM feel free to work on this PR. This is stale for around 1 year. You can either create a new PR following the latest template, or can start from this Pull request.

**Comment by LalitNM** [comment]
Closing this due to inactivity of PR.

**Pull request closed without merging**
