### PR TITLE
Changed requirements and contributing guidelines

### PR DESCRIPTION
**Pull request by gajrajgchouhan**

### CODE REVIEW

**Comment by harnaman-hk** [comment]
As this PR solves an issue, you can link it to the issue by referencing the issue in the description of your pull request. For example,
Fixes #124 
This practice closes the issue upon merging the PR.

**Comment by LalitNM** [comment]
@gajrajgchouhan can you make separate commits for these changes? This will help us in maintaining a clean git history.

**Review by harnaman-hk — APPROVED** [review]

**Comment by gajrajgchouhan** [comment]
> As this PR solves an issue, you can link it to the issue by referencing the issue in the description of your pull request. For example,
> Fixes #124
> This practice closes the issue upon merging the PR.

But I haven't added the instructions for Windows OS, so I didn't reference it.

**Comment by LalitNM** [comment]
Checking if commenting helps in reopening PR.

**Pull request closed without merging**
