### PR TITLE
Added template!

### PR DESCRIPTION
**Pull request by gajrajgchouhan**
#137

### CODE REVIEW

**Comment by LalitNM** [comment]
I think we can simply add cdns for bootstrap, no need to put all `.min.css` and `.min.js` files. You cam simply put a `.html` file with link to cdn of bootstrap-css and js.

**Comment by harnaman-hk** [comment]
Any specific reason for creating a new route and not having it in home.html?

**Comment by LalitNM** [comment]
Some more changes which can be done in order to improve this pull request:

- I don't think we need this much code in every file, for example you can remove `navbar`, `head imports`, `footer imports` from main page and can shift them to some files like `navbar.html`, `head_imports.html`, `footer_imports.html`.

- You can include all cdn javascript file in `footer_imports`(not in `<head>` as they are supposed to load after whole document or add a `defer` attribute to `script`.

- You can add a functionality to update the copyright year using javascript, in this way we can get rid of one pull request to update copyright every year.

- Can you remove unnecessary stac_iitmandi folder in `src/stac_iitmandi/static`, i don't think it has some use.

- At present the navbar is at the top of the body, could you give it some style and make it look like some content floating in the space, like 
galaxy1

**Comment by gajrajgchouhan** [comment]
> Any specific reason for creating a new route and not having it in home.html?

Like the previous site, it had the template in `template.html`. So I added a route to the template.

**Comment by gajrajgchouhan** [comment]
@LalitNM `static` folder has all the CSS, JS, image files we may load in the html page. Presently it only has the image and `style.css`

**Comment by gajrajgchouhan** [comment]
> Some more changes which can be done in order to improve this pull request:
> 
> * I don't think we need this much code in every file, for example you can remove `navbar`, `head imports`, `footer imports` from main page and can shift them to some files like `navbar.html`, `head_imports.html`, `footer_imports.html`.
Can we instead make one and then use `extends` everywhere else to load it ?
> * You can include all cdn javascript file in `footer_imports`(not in `<head>` as they are supposed to load after whole document or add a `defer` attribute to `script`.
But JS CDNs are not present in `<head>` here ?
> * You can add a functionality to update the copyright year using javascript, in this way we can get rid of one pull request to update copyright every year.
Will do.
> * At present the navbar is at the top of the body, could you give it some style and make it look like some content floating in the space, like
>   galaxy1
Okay

**Comment by LalitNM** [comment]
> Can we instead make one and then use extends everywhere else to load it ?

Yeah, that's what I meant :+1:

> But JS CDNs are not present in `<head>` here ?

Great, then you just need to put them in separate file.

**Comment by LalitNM** [comment]
This looks great @gajrajgchouhan :clap:. Merging this :rocket:

**Pull request merged**
