### PR TITLE
Modify banner.

### PR DESCRIPTION
**Pull request by akshat157**
Please review the modifications to done on the banner.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Post some screenshot of the index.html when opened in browser :)

**Comment by shreyasbapat** [comment]
Rebase your branch! 
``git remote add upstream https://github.com/STAC-IITMandi/STAC-IITMandi.github.io.git``
``git checkout master``
``git fetch upstream``
``git rebase upstream/master``
``git checkout banner``
``git rebase master``

Then run the prettify-HTML-CSS-JS  again.
And commit the changes. I guess merge conflics would occur

**Comment by akshat157** [comment]
Added another PR, you can check it.

**Comment by shreyasbapat** [comment]
Closed due to #13

**Pull request closed without merging**
