### PR TITLE
changed some rules

### PR DESCRIPTION
**Pull request by jeel2308**
i have changed some rules.Now it looks like this
layout2

in previous comment i said that i can fix the bug using flex/grid but i can not do it.sorry for it.
hope you will like this one.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
I am very sure we can't accept this!
Still, will check with others :)

**Comment by shreyasbapat** [comment]
I am afraid we can't!
@akashdakoor @akshat157

**Comment by akshat157** [comment]
The design is good but won't suit the website IMO. I'd have preferred this one if the cards were required descrete focus of the viewer. Or there was a priority order. Not the case here hence as @shreyasbapat said, it'd be difficult for us to accept this.

**Comment by LalitNM** [comment]
Closing this because we can't accept such styling.

**Pull request closed without merging**
