### PR TITLE
Copyright update

### PR DESCRIPTION
**Pull request by Muzzammil15**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Please address both the issues separately!

**Comment by shreyasbapat** [comment]
I would suggest making a different branch for different issues!

**Comment by Muzzammil15** [comment]
okay appologies about it, i will re work on it by this afternoon

**Comment by Muzzammil15** [comment]
screen shot 2018-03-26 at 11 28 26
I have fixed copyright footer on each pages 
i can't re address the issue because i have already worked on the files

but all the pages has been updated with new copyright info

you can accept the commit

**Pull request closed without merging**
