### PR TITLE
feature: added text slider.

### PR DESCRIPTION
**Pull request by chandan1794**
For the #50.
**Status**: Not completed

1.  Needs suggestion on the content
2. How should it behave on smaller screens?
3. Is full-screen banner looking good?

### CODE REVIEW

**Comment by shreyasbapat** [comment]
I will put some insights on this once I get back to Mandi. I have some nice Ideas!😃

**Comment by chandan1794** [comment]
> I will put some insights on this once I get back to Mandi. I have some nice Ideas!😃

Sure :)

**Comment by shreyasbapat** [comment]
Before proceeding further, I guess you are commiting through a wrong email id! 
Change the author of the commit you just made.
You can do that by typing:
`git commit --amend --author="Chandan Purbia <kingpurbiaforever@gmail.com>"`

**Comment by shreyasbapat** [comment]
1)After you do that, can you please put some random content? @akashdakoor will edit the content in a way he wants!
2)On smaller screens, maybe it just turns to two buttons, follow on facebook and see github? Which can then be changed to `Show Zenith Events` whenever neccesary!
3)I am not sure! Perhaps @akshat157 can add something to it! But we can explore about the options!

**Comment by shreyasbapat** [comment]
You will now need to rebase as well :)
image

I can help you with that! If you feel.

**Comment by LalitNM** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
