### PR TITLE
Adding team

### PR DESCRIPTION
**Pull request by LalitNM**
I have added html and images for team page. Although it needs improvement. Need suggestion :p

### CODE REVIEW

**Comment by LalitNM** [comment]
@ArshitaKalra I have added link to each member's Facebook. Also, I have added box-shadow on hover.

**Comment by LalitNM** [comment]
@abhijeetmanhas now everything is solved.
A screenshot for reference:
team
@ArshitaKalra have a look.

**Comment by abhijeetmanhas** [comment]
Screenshot from 2020-04-30 02-04-07

@LalitNM I know it have took a lot of time to make those changes, but it is an accepted norm that we do not change the height:width ratio of image, (I don't know what is exact word for it) . Compare the original, you can find the difference.

**Comment by LalitNM** [comment]
@abhijeetmanhas thanks for your suggestion. It was really not good to change aspect ratio of any image. Now I have modified whole document. Hope it will be accepted this time 😅.
Have a look at a screenshot
Team

**Comment by abhijeetmanhas** [comment]
Thanks @LalitNM for this, it is complete, I'll do little rearrangement of members, rest is fine.

**Comment by LalitNM** [comment]
I did some minor style changes after a discussion with @ArshitaKalra.
@ArshitaKalra. Have a look.

**Pull request merged**
