### PR TITLE
Footers center aligned

### PR DESCRIPTION
**Pull request by DumbMachine**

### CODE REVIEW

**Comment by DumbMachine** [comment]
[Desktop View](https://user-images.githubusercontent.com/23381512/51103729-d3e0ad00-1809-11e9-86ed-8eaa72645119.png)
[Mobile View](https://user-images.githubusercontent.com/23381512/51103774-f5da2f80-1809-11e9-9cec-bd050dbfd894.png)

**Comment by shreyasbapat** [comment]
Thanks a lot for the contribution @DumbMachine ! 🚀

**Comment by DumbMachine** [comment]
It was fun contributing😊.

**Comment by shreyasbapat** [comment]
@DumbMachine You are welcome and encouraged to solve any issues here. We would be glad to have you on board :)

**Pull request merged**
