### PR TITLE
Removed unnecessary 404 page

### PR DESCRIPTION
**Pull request by LalitNM**
I have removed unnecessary 404 page.

### CODE REVIEW

**Comment by LalitNM** [comment]
@shreyasbapat I tried to solve #75

**Comment by shreyasbapat** [comment]
I get too many GitHub Notifications @LalitNM . Sorry for the late reply. You need to rebase!

**Comment by LalitNM** [comment]
@shreyasbapat What exactly I am supposed to do?
Should I merge this branch in some other branch of mine.... or something else?
I am new to opensource ans still have a long way to go. 😅

**Comment by abhijeetmanhas** [comment]
> @shreyasbapat What exactly I am supposed to do?
> Should I merge this branch in some other branch of mine.... or something else?
> I am new to opensource and still have a long way to go.
on your branch, do this.
You should have this remote repo as upstream first.
`git fetch upstream master`
`git rebase upstream/master`
and then
`git push -f origin ErrorPage`
Read more about rebasing btw.

**Comment by shreyasbapat** [comment]
The right way to do it usually is to rebase the master.
```
git checkout master
```
Do everything @abhijeetmanhas mentioned prior to push,

and then,

```
$ git checkout Errorpage
$ git rebase master
```
And then push. 

Now there are 1000 ways to rebase, and every one of them has some downside.

**Comment by LalitNM** [comment]
I did rebase and push.
But, why we are not just deleting the commit made for this error page using interactive rebase. Then we will have cleaner git history.

**Pull request closed without merging**
