### PR TITLE
Update home-page

### PR DESCRIPTION
**Pull request by ArshitaKalra**
I have made some changes on the home page . Please review them on https://arshitak.com/STAC-IITMandi.github.io/ @shreyasbapat @akshat157 @abhijeetmanhas  .

### CODE REVIEW

**Comment by shreyasbapat** [comment]
It would be nice to have a central body and all the planets already having elliptical or circular orbits around that!

**Comment by shreyasbapat** [comment]
I mean when it begins! Moreover, a brief caption about what's happening in the animations in the lower side of the banner will be cool! :D BTW Great!

**Comment by shreyasbapat** [comment]
Also, review the mobile compatibility of the Hashtag!
image

**Comment by kartik1000** [comment]
For mobile compatability you can look into [https://www.w3schools.com/css/css_rwd_mediaqueries.asp](url)

**Pull request merged**
