### PR TITLE
Add popup for broken links

### LINKED ISSUE #67: Some links and buttons are not responsive
**Describe the bug**
Some links and buttons are not responsive. Like **Inventory** in the nav-bar, **Archives**, **Alumni** and **Administer** in the footer. This is not user-friendly. Either we should remove them and show them when they are functioning properly or we should give a message indicating that we are still working on it.

**To Reproduce**
1. Go to any page of the website
2. Click on the above-mentioned links

**Expected behavior**
Should redirect to the intended pages.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by matheusagcosta**
@akshat157 @shreyasbapat 

Closes #67 
 
Screen Shot 2019-10-01 at 19 22 34

### CODE REVIEW

**Comment by abhijeetmanhas** [comment]
@akshat157 doesn't it looks big? Or covers content? What's your suggestion?

**Comment by akshat157** [comment]
Its way too big.

perhaps, reduce the padding would work. Also, the font size in the popup can be smaller than that of the hyperlinks. :)

**Comment by matheusagcosta** [comment]
@abhijeetmanhas @akshat157 The font size it's already smaller than the hyperlinks but I've reduced one more pixel.

I've also reduced the box padding. 

Please take a look and let me know if that looks better.

image

**Comment by LalitNM** [comment]
@akshat157 and @abhijeetmanhas can we add modals to solve this problem?

**Comment by matheusagcosta** [comment]
Closing the PR

**Pull request closed without merging**
