### PR TITLE
Event page added with bootstrap

### PR DESCRIPTION
**Pull request by Muzzammil15**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
@Muzzammil15  Can you share some screenshot of the webpage! Just for us to know how it looks like

**Comment by shreyasbapat** [comment]
Another thing! Give proper description to the PR. This eases the job of the reviewer!

**Comment by Muzzammil15** [comment]
screen shot 2018-03-25 at 23 21 53
screen shot 2018-03-26 at 09 10 37

**Comment by Muzzammil15** [comment]
screen shot 2018-03-26 at 09 10 54

**Comment by Muzzammil15** [comment]
if you feel the design is okay for the event page, then we can add a lightbox where user can open poster large thus can see it more properly

**Comment by shreyasbapat** [comment]
Yeah! Please do it and add another commit ! :)

**Pull request closed without merging**
