### PR TITLE
Fix Activities logo

### PR DESCRIPTION
**Pull request by MADPT**
Activities logo fixed

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Please Rebase!

**Comment by shreyasbapat** [comment]
And kindly send 2 screenshots of what it looks like now. One for the desktop view, and one for mobile view.(You can resize your browser for mobile view)

**Comment by MADPT** [comment]
I've already rebased and here are two screenshots:

Desktop
captura de ecra 2018-10-01 as 15 25 57

Mobile
captura de ecra 2018-10-01 as 15 26 37

**Comment by shreyasbapat** [comment]
Great! GTG!

**Comment by shreyasbapat** [comment]
@akashdakoor See this!

**Pull request merged**
